<a href="https://colab.research.google.com/github/vikramgunjal02/Machine-Learning/blob/master/demoipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
l=np.array(range(2,10))
print(l)

[2 3 4 5 6 7 8 9]


In [4]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(2,22,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
l=np.arange(1,8)
l

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
l[1:5]

array([2, 3, 4, 5])

In [23]:
l[::5]

array([1, 6])